import Head from "next/head";
import { Inter } from "next/font/google";
import Login from '@/pages/components/Login';
import { useEffect } from "react";



const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  // useEffect(() => {
  //    connectToDatabase();
  //  },[])
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Login/>

      


    </>
  );
}
